export enum ErrorCode {
  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',

  // Resource
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Chat
  CHAT_ROOM_NOT_FOUND = 'CHAT_ROOM_NOT_FOUND',
  CHAT_MESSAGE_NOT_FOUND = 'CHAT_MESSAGE_NOT_FOUND',
  CHAT_PLATFORM_NOT_FOUND = 'CHAT_PLATFORM_NOT_FOUND',
  CHAT_INVALID_WEBHOOK = 'CHAT_INVALID_WEBHOOK',

  // Room
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  PLATFORM_SEND_FAILED = 'PLATFORM_SEND_FAILED',
  PLATFORM_NOT_CONFIGURED = 'PLATFORM_NOT_CONFIGURED',

  // Shop
  SHOP_NOT_FOUND = 'SHOP_NOT_FOUND',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_VALIDATION_ERROR = 'USER_VALIDATION_ERROR',

  // Credential
  CREDENTIAL_NOT_FOUND = 'CREDENTIAL_NOT_FOUND',

  // Customer Identity
  CUSTOMER_IDENTITY_NOT_FOUND = 'CUSTOMER_IDENTITY_NOT_FOUND',

  // User Platform
  USER_PLATFORM_NOT_FOUND = 'USER_PLATFORM_NOT_FOUND',

  // Internal
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
